name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --extras all
        make clean

    - name: Lint with pysen
      run: |
        make lint

    - name: Test with pytest
      run: |
        make test
